name: Push-to-EC2 # Any name you want to set

# Trigger deployment only on push and pull request to main branch
on:
  push:
    branches: [ main ] # Branch name
  pull_request:
    branches: [ main ] # Branch name

jobs:
  build:
    name: Deploy to EC2
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Env file copy from /home/ubuntu to project
        run: |
              scp /home/ubuntu/.env ./
      - name: Install NPM dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build
      - name: Run Next.js app
        run: sudo npx pm2 start npm --  start
      # - name: Stop Next.js app
      #   run: npx pm2 kill